---
- hosts: Webservers
  tasks:
   - name: install the latest version of Apache
     yum:
       name: "{{ item }}"
       state: latest
     loop:
       - httpd
       - mariadb-server
   - name: example copying file with owner and permissions
     copy:
       src: /home/ec2-user/environment/index.html
       dest: /var/www/html/
       owner: ec2-user
       group: ec2-user
       mode: 0644
     copy:
       src: /home/ec2-user/environment/Dev/httpd.conf
       dest: /etc/httpd/conf/httpd.conf
       owner: ec2-user
       group: ec2-user
       mode: 0644
     notify: restart services
  handlers:
   - name: restart services
     service:
       name: "{{ item }}"
       state: restarted
     loop:
       - httpd
       - mariadb
